name: 'dbtlearn'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbtlearn'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Configuring models
models:
  dbtlearn:
    # Config indicated by + and applies to all files under models/staging/
    staging:
      +materialized: view
      +schema: staging
    # Config for models under models/marts/
    marts:
      +materialized: table
      +schema: marts

vars:
  # Variable for setting date ranges in development
  start_date: '2019-01-01'

# Seeds configuration
seeds:
  dbtlearn:
    +schema: raw
