models:
  - name: dim_listings_cleansed
    description: Cleansed table containing Airbnb listing information.
    data_tests:
      - minimum_row_count:
          arguments:
            min_row_count: 1000
          config:
            severity: error
    columns:
      - name: listing_id
        description: Primary key for the listings table.
        data_tests:
          - unique
          - not_null
      - name: host_id
        description: The hosts's id. References the host table.
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id
      - name: room_type
        description: Type of the apartment / room
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [ 'Entire home/apt', 'Private room', 'Shared room', 'Hotel room' ]
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        data_tests:
          - positive_values

  - name: dim_hosts_cleansed
    description: Cleansed table containing Airbnb host information.
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        description: Primary key for the hosts table.
        data_type: integer
      - name: host_name
        description: Name of the host.
        data_type: string
      - name: is_superhost
        description: Indicates if the host is a superhost.
        data_type: string
      - name: updated_at
        description: Timestamp when the host information was last updated.
        data_type: timestamp
      - name: created_at
        description: Timestamp when the host information was created.
        data_type: timestamp

  - name: dim_listings_w_hosts
    description: Table combining cleansed listings with cleansed host information.
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          arguments:
            compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        description: Price of the listing.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: number
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              arguments:
                quantile: 0.99
                min_value: 50
                max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              config:
                severity: warn
              arguments:
                max_value: 5000
  - name: mart_fullmoon_reviews
    description: The mart_fullmoon_reviews model provides insights into customer reviews by identifying whether they occurred during a full moon or not. This information can help businesses analyze patterns in customer sentiment and behavior, potentially uncovering unique trends associated with lunar phases. By leveraging this model, businesses can make informed decisions to optimize customer engagement strategies and improve overall service quality.
    columns:
      - name: review_id
        description: A unique identifier for each review in the dataset.
        data_type: varchar
      - name: listing_id
        description: A unique identifier for the Airbnb listing associated with the review.
        data_type: number
        data_tests:
          - unique
      - name: review_date
        description: The timestamp indicating the date and time when the review was submitted.
        data_type: timestamp_ntz
      - name: reviewer_name
        description: The name of the individual who provided the review for the listing.
        data_type: varchar
      - name: review_text
        description: The text content of the review provided by the reviewer, detailing their experience or feedback about the listing.
        data_type: varchar
      - name: review_sentiment
        description: Indicates the sentiment of the review text, typically categorized as positive, negative, or neutral based on the content of the review.
        data_type: varchar
      - name: is_full_moon
        description: Indicates whether the review date falls on or one day after a full moon. Possible values are 'full moon' and 'not full moon'.
        data_type: varchar
  - name: fct_reviews
    description: The fct_reviews model processes raw review data from the Airbnb source, transforming it into a structured format for analysis. It includes details such as the listing ID, review date, reviewer name, review text, and sentiment analysis of the review. Additionally, a unique review ID is generated for each record to ensure data integrity and facilitate tracking.
    columns:
      - name: review_id
        description: A unique identifier for each review, generated using a hash of the listing ID, review date, reviewer name, and review text.
        data_type: varchar
      - name: listing_id
        description: The unique identifier for the Airbnb listing associated with the review.
        data_type: number
      - name: review_date
        description: The date when the review was submitted.
        data_type: timestamp_ntz
      - name: reviewer_name
        description: The name of the individual who provided the review for the listing.
        data_type: varchar
      - name: review_text
        description: The textual content of the review provided by the reviewer, describing their experience or feedback.
        data_type: varchar
      - name: review_sentiment
        description: The sentiment analysis result of the review text, indicating whether the review is positive, negative, or neutral.
        data_type: varchar
