models:
  - name: dim_listings_cleansed
    description: Cleansed table containing Airbnb listing information.
    data_tests:
      - minimum_row_count:
          arguments:
            min_row_count: 1000
          config:
            severity: error
    columns:
      - name: listing_id
        description: Primary key for the listings table.
        data_tests:
          - unique
          - not_null
      - name: host_id
        description: The hosts's id. References the host table.
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id
      - name: room_type
        description: Type of the apartment / room
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [ 'Entire home/apt', 'Private room', 'Shared room', 'Hotel room' ]
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        data_tests:
          - positive_values

  - name: dim_hosts_cleansed
    description: Cleansed table containing Airbnb host information.
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        description: Primary key for the hosts table.
        data_type: integer
      - name: host_name
        description: Name of the host.
        data_type: string
      - name: is_superhost
        description: Indicates if the host is a superhost.
        data_type: string
      - name: updated_at
        description: Timestamp when the host information was last updated.
        data_type: timestamp
      - name: created_at
        description: Timestamp when the host information was created.
        data_type: timestamp

  - name: dim_listings_w_hosts
    description: Table combining cleansed listings with cleansed host information.
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          arguments:
            compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        description: Price of the listing.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: number
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              arguments:
                quantile: 0.99
                min_value: 50
                max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              config:
                severity: warn
              arguments:
                max_value: 5000
  - name: mart_fullmoon_reviews
    description: sample description for mart_fullmoon_reviews model
