version: 2

models:
  - name: dim_customers
    description: Customer dimension with lifetime value metrics
    columns:
      - name: customer_id
        description: Primary key for customers
        tests:
          - unique
          - not_null

      - name: customer_name
        description: Full name of the customer
        tests:
          - not_null

      - name: customer_email
        description: Customer email address
        tests:
          - not_null

      - name: customer_created_at
        description: Date when customer account was created
        tests:
          - not_null

      - name: total_orders
        description: Total number of orders by customer

      - name: completed_orders
        description: Number of completed orders

      - name: lifetime_value
        description: Total value of all completed orders

      - name: first_order_date
        description: Date of first order

      - name: most_recent_order_date
        description: Date of most recent order

  - name: fct_orders
    description: Order fact table with enriched information
    columns:
      - name: order_id
        description: Primary key for orders
        tests:
          - unique
          - not_null

      - name: customer_id
        description: Foreign key to customers
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id

      - name: customer_name
        description: Customer full name

      - name: customer_email
        description: Customer email address

      - name: order_date
        description: Date when order was placed
        tests:
          - not_null

      - name: order_status
        description: Current status of the order
        tests:
          - not_null

      - name: order_amount
        description: Order amount from order system

      - name: payment_amount
        description: Calculated payment amount from line items

      - name: unique_products
        description: Number of unique products in order

      - name: total_items
        description: Total quantity of items in order
